import type { Metadata } from "next";
import { Link } from "@/i18n/navigation";
import {
  EditorialHero,
  EditorialPageShell,
  EditorialSection,
} from "@/components/editorial/EditorialPage";
import { EDITORIAL_STYLES } from "@/components/editorial/editorialStyles";

const siteUrl = "https://thememorychess.com";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The plain-language terms for playing Memory Chess, submitting leaderboard scores, and using the site's content.",
  // Placeholder: replaced with buildAlternates once the page is translated.
  // Kept as a plain canonical so nothing points at a locale that does not yet
  // differ in content.
  alternates: {
    canonical: "/terms",
  },
  openGraph: {
    title: "Memory Chess Terms of Service",
    description:
      "The plain-language terms for playing Memory Chess and using the site.",
    url: `${siteUrl}/terms`,
  },
  twitter: {
    title: "Memory Chess Terms of Service",
    description:
      "The plain-language terms for playing Memory Chess and using the site.",
  },
};

export default function TermsPage() {
  return (
    <EditorialPageShell>
      <EditorialHero
        eyebrow="The fine print"
        title="Terms of Service"
        description="Memory Chess is a free game run by one person. These terms are short because the deal is simple, and they are written to be read."
      />

      <div className={EDITORIAL_STYLES.readingColumn}>
        <EditorialSection title="The service">
            <p>
              Memory Chess is a free browser game for training board memory. I
              provide it as-is and as-available, with no warranty of any kind.
              I work to keep it fast, accurate, and online, but I do not
              promise uninterrupted service, error-free scoring, or that any
              feature will stay the same forever. I may change, suspend, or
              discontinue any part of the site at any time.
            </p>
            <p>
              To the extent permitted by law, I am not liable for damages
              arising from your use of the site. It is a memory game. The
              sensible ceiling on what can go wrong here is losing a score you
              cared about, and I still try hard to prevent that.
            </p>
        </EditorialSection>

        <EditorialSection title="Acceptable use">
            <p>
              Play fairly and leave the site working for everyone else. Do not
              attack, overload, or probe the service, scrape it at volume, or
              try to break its scoring. Do not submit scores generated by bots,
              scripts, or automation of any kind. Do not use the contact form
              or leaderboard to spam, harass, or impersonate anyone.
            </p>
            <p>
              The contact form is for real messages to a real person. Use it
              for bug reports, questions, and ideas, and it will be read.
            </p>
            <p>
              I may block traffic or restrict access that violates these rules.
              With no accounts to ban, removing bad entries and blocking abuse
              at the edge is the enforcement I have, and I use it.
            </p>
        </EditorialSection>

        <EditorialSection title="The leaderboard">
            <p>
              Submitting a score to the leaderboard is optional. Anything you
              submit there is public. The name attached to a score is whatever
              you type in, so pick something you are happy to see published,
              and do not use your real name or anyone&apos;s personal
              information if you would rather keep it private.
            </p>
            <p>
              A submitted entry holds the name you chose and the details of the
              round, such as accuracy, difficulty, and completion time. Once
              published it stays on the board until it is displaced by better
              scores or removed.
            </p>
            <p>
              I may remove leaderboard entries that are abusive, that
              impersonate someone, that appear automated, or that were clearly
              not produced by a person playing the game. I remove entries to
              keep the board honest, not to curate who wins.
            </p>
        </EditorialSection>

        <EditorialSection title="Content and intellectual property">
            <p>
              The site&apos;s own content, including the game, the Learn
              guides, the design, and the code that runs it, belongs to me. You
              are welcome to link to any page, quote reasonable excerpts with
              attribution, and share your scores anywhere you like. Do not
              republish whole guides or pass the site&apos;s content off as
              your own.
            </p>
            <p>
              Chess itself belongs to nobody. Positions, rules, and notation
              are free for everyone, here and everywhere else.
            </p>
            <p>
              If you send feedback or suggestions, you agree that I can use
              them to improve the site without owing you compensation or
              credit. Player feedback has shaped real releases before, and the
              changelog records what came of it.
            </p>
        </EditorialSection>

        <EditorialSection title="Third-party services">
            <p>
              The site runs on a small set of external services. Google AdSense
              serves the ads that keep it free. Google Analytics, Vercel
              Analytics, Vercel Speed Insights, and Ahrefs Analytics measure
              traffic and performance. Supabase stores game statistics and
              leaderboard entries. Each has its own terms, and the{" "}
              <Link href="/privacy" className={EDITORIAL_STYLES.link}>
                privacy policy
              </Link>{" "}
              explains what data each one touches and the choices you have.
            </p>
        </EditorialSection>

        <EditorialSection title="Changes to these terms">
            <p>
              I may update these terms when the site or its services change. The
              current version always lives at this address, and continuing to
              use the site after a change means you accept the updated terms.
              For anything that meaningfully affects players, such as a change
              to how the leaderboard works, I note it in the changelog as well.
            </p>
        </EditorialSection>

        <EditorialSection title="Contact">
            <p>
              Questions about these terms, or a leaderboard entry you want
              reviewed or removed, go to{" "}
              <a
                href="mailto:bingcheng45@gmail.com"
                className={EDITORIAL_STYLES.link}
              >
                bingcheng45@gmail.com
              </a>
              . I answer them myself.
            </p>
        </EditorialSection>
      </div>
    </EditorialPageShell>
  );
}
