// Generated by scripts/generate-showcase-reach.mjs from the Bonn game record. Do not edit.
import type { ShowcaseReach } from "./showcase";

export const SHOWCASE_REACH: ShowcaseReach = {
  f8: {
    attacks: ["d7", "e6", "g6", "h7"],
    legal: [
      { to: "h7", san: "Nh7" },
      { to: "g6", san: "Ng6+" },
      { to: "e6", san: "Ne6" },
      { to: "d7", san: "Nd7" },
    ],
  },
  h8: {
    attacks: ["g7", "g8", "h7"],
    legal: [
      { to: "g8", san: "Kg8" },
    ],
  },
  a7: {
    attacks: ["a4", "a5", "a6", "a8", "b6", "b7", "b8", "c5", "c7", "d4", "d7", "e3", "e7", "f2", "f7", "g1", "g7"],
    legal: [
      { to: "a8", san: "Qa8" },
      { to: "b8", san: "Qb8" },
      { to: "b7", san: "Qb7" },
      { to: "c7", san: "Qc7" },
      { to: "d7", san: "Qd7" },
      { to: "e7", san: "Qe7" },
      { to: "f7", san: "Qf7" },
      { to: "b6", san: "Qb6" },
      { to: "c5", san: "Qc5" },
      { to: "d4", san: "Qd4" },
      { to: "e3", san: "Qe3" },
      { to: "f2", san: "Qf2" },
      { to: "g1", san: "Qg1+" },
      { to: "a6", san: "Qa6" },
      { to: "a5", san: "Qa5" },
    ],
  },
  g7: {
    attacks: ["f6", "h6"],
    legal: [
      { to: "g6", san: "g6" },
      { to: "g5", san: "g5" },
    ],
  },
  h6: {
    attacks: ["g5"],
    legal: [
      { to: "h5", san: "h5" },
    ],
  },
  e5: {
    attacks: ["d6", "f6"],
    legal: [
      { to: "e6", san: "e6" },
    ],
  },
  a4: {
    attacks: ["b3"],
    legal: [
      { to: "a3", san: "a3" },
    ],
  },
  b4: {
    attacks: ["a3", "c3"],
    legal: [
      { to: "b3", san: "b3" },
    ],
  },
  e4: {
    attacks: ["a8", "b1", "b4", "b7", "c2", "c4", "c6", "d3", "d4", "d5", "e1", "e2", "e3", "e5", "f3", "f4", "f5", "g2", "g4", "g6", "h4", "h7"],
    legal: [
      { to: "d5", san: "Qd5" },
      { to: "c6", san: "Qc6" },
      { to: "b7", san: "Qb7" },
      { to: "a8", san: "Qa8" },
      { to: "f5", san: "Qf5" },
      { to: "g6", san: "Qg6" },
      { to: "h7", san: "Qh7#" },
      { to: "f4", san: "Qf4" },
      { to: "g4", san: "Qg4" },
      { to: "h4", san: "Qh4" },
      { to: "f3", san: "Qf3" },
      { to: "e3", san: "Qe3" },
      { to: "e2", san: "Qe2" },
      { to: "e1", san: "Qe1" },
      { to: "d3", san: "Qd3" },
      { to: "c2", san: "Qc2" },
      { to: "b1", san: "Qb1" },
      { to: "d4", san: "Qd4" },
      { to: "c4", san: "Qc4" },
      { to: "b4", san: "Qxb4" },
    ],
  },
  b2: {
    attacks: ["a3", "c3"],
    legal: [
      { to: "b3", san: "b3" },
    ],
  },
  g2: {
    attacks: ["f3", "h3"],
    legal: [
      { to: "g3", san: "g3" },
      { to: "g4", san: "g4" },
    ],
  },
  h2: {
    attacks: ["g3"],
    legal: [
      { to: "h3", san: "h3" },
      { to: "h4", san: "h4" },
    ],
  },
  c1: {
    attacks: ["b2", "d2", "e3", "f4", "g5", "h6"],
    legal: [
      { to: "b2", san: "Bxb2" },
      { to: "d2", san: "Bd2" },
      { to: "e3", san: "Be3" },
      { to: "f4", san: "Bf4" },
      { to: "g5", san: "Bg5" },
    ],
  },
  h1: {
    attacks: ["g1", "g2", "h2"],
    legal: [],
  },
};
